trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore AgentWebApp/AgentWebApp.csproj
  displayName: 'Restore dependencies'

- script: dotnet build AgentWebApp/AgentWebApp.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'Build'

- script: dotnet test AgentWebApp/AgentWebApp.csproj --no-build --verbosity normal
  displayName: 'Test'

- script: dotnet publish AgentWebApp/AgentWebApp.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'FirstServiceConnection'
    appType: 'webApp'
    appName: 'AgentApp'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

- task: PublishBuildArtifacts@1