trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore AgentWebApp/AgentWebApp.csproj
  displayName: 'Restore dependencies'

- script: dotnet build AgentWebApp/AgentWebApp.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'Build'

- script: dotnet test AgentWebApp/AgentWebApp.csproj --no-build --verbosity normal
  displayName: 'Test'

- script: dotnet publish AgentWebApp/AgentWebApp.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'FirstServiceConnection'
#     appType: 'webApp'
#     appName: 'AgentApp'
#     package: '$(Build.ArtifactStagingDirectory)/IocContainer.zip'

# 1. Publish the project
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

# 2. Archive the published output as a ZIP
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/AgentWebApp.zip'
    replaceExistingArchive: true

# 3. Publish the ZIP as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/AgentWebApp.zip'
    artifactName: 'drop'

# 4. Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'FirstServiceConnection'
    appType: 'webApp'
    appName: 'AgentApp'
    package: '$(Pipeline.Workspace)/drop/AgentWebApp.zip'
