name: .NET 8 CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore AgentWebApp/AgentWebApp.csproj

    - name: Build
      run: dotnet build AgentWebApp/AgentWebApp.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test AgentWebApp/AgentWebApp.csproj --no-build --verbosity normal

    - name: Publish
      run: dotnet publish AgentWebApp/AgentWebApp.csproj --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./publish

    # Uncomment and configure the following steps for Azure Web App deployment
    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: <YOUR_AZURE_WEBAPP_NAME>
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: ./publish